name: promptSummer
channels:  
 - defaults
dependencies:  
 - python=3.12.0
 - openai
 - python-dotenv
 - pip
 - openai
 - pip:
   - crewai
   - crewai[tools]
   - langchain
   - langchain-community
   - langchain-core
   - langchain-openai
   - langchain_aws
   - boto3

